steps:
  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/gforce-docs:$COMMIT_SHA', '.']
    dir: '.'

  - id: 'Push Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/gforce-docs:$COMMIT_SHA']

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'gforce-docs',
      '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/gforce-docs:$COMMIT_SHA',
      '--region', 'europe-west1',
      '--platform', 'managed'
    ]

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-repo/gforce-docs:$COMMIT_SHA'